// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBptrRs3A_mEqKl5A3f8DtS9UqOH3N8k1U',
    appId: '1:107842674054:android:6795ce635e03b395026007',
    messagingSenderId: '107842674054',
    projectId: 'auth-all-64720',
    databaseURL: 'https://auth-all-64720-default-rtdb.firebaseio.com',
    storageBucket: 'auth-all-64720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtwi1qxtKbgmxRyUHrlsDR3_d8rkZU_O0',
    appId: '1:107842674054:ios:04541f14fe8bd729026007',
    messagingSenderId: '107842674054',
    projectId: 'auth-all-64720',
    databaseURL: 'https://auth-all-64720-default-rtdb.firebaseio.com',
    storageBucket: 'auth-all-64720.appspot.com',
    androidClientId: '107842674054-cc4v8c9023naa32qkhg9n23ncog8td8n.apps.googleusercontent.com',
    iosClientId: '107842674054-7vr5hl55tf6cmmbhj2mr0c8f61honm1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtwi1qxtKbgmxRyUHrlsDR3_d8rkZU_O0',
    appId: '1:107842674054:ios:04541f14fe8bd729026007',
    messagingSenderId: '107842674054',
    projectId: 'auth-all-64720',
    databaseURL: 'https://auth-all-64720-default-rtdb.firebaseio.com',
    storageBucket: 'auth-all-64720.appspot.com',
    androidClientId: '107842674054-cc4v8c9023naa32qkhg9n23ncog8td8n.apps.googleusercontent.com',
    iosClientId: '107842674054-7vr5hl55tf6cmmbhj2mr0c8f61honm1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pricAssigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuuVp4CarfuR44TSvgeD5xpkV_hi-q6sg',
    appId: '1:107842674054:web:c26d131d9c4f7771026007',
    messagingSenderId: '107842674054',
    projectId: 'auth-all-64720',
    authDomain: 'auth-all-64720.firebaseapp.com',
    databaseURL: 'https://auth-all-64720-default-rtdb.firebaseio.com',
    storageBucket: 'auth-all-64720.appspot.com',
    measurementId: 'G-YK0QRLNQLP',
  );
}
